/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../fstar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -bundle GC.Impl+GC.Impl.Allocator=GC.Impl.*[rename=GC_Impl] -bundle FStar.Pervasives.Native -bundle GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Impl -no-prefix GC.Impl.Mark -no-prefix GC.Impl.MarkBounded -no-prefix GC.Impl.Sweep -no-prefix GC.Impl.Fields -no-prefix GC.Impl.Closure -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -no-prefix GC.Impl.Allocator -no-prefix GC.Impl.FusedSweepCoalesce -no-prefix GC.Impl.Coalesce -warn-error -2-9-15 _output/GC_Impl_Fields.krml _output/GC_Impl_Closure.krml _output/GC_Impl_Mark.krml _output/GC_Impl_MarkBounded.krml _output/GC_Impl_Sweep.krml _output/GC_Impl_Coalesce.krml _output/GC_Impl_FusedSweepCoalesce.krml _output/GC_Impl.krml _output/GC_Impl_Allocator.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml _output/FStar_Pervasives_Native.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#include "internal/GC_Impl.h"

#include "internal/GC_Spec_GC_Lib_Header_GC_Lib_Address.h"

static uint64_t mword = 8ULL;

/* heap_size_u64: defined by the application (e.g., main.c) */

static uint64_t zero_addr = 0ULL;

static uint8_t uint64_to_uint8(uint64_t x)
{
  return (uint8_t)x;
}

static uint64_t
combine_bytes(
  uint8_t b0,
  uint8_t b1,
  uint8_t b2,
  uint8_t b3,
  uint8_t b4,
  uint8_t b5,
  uint8_t b6,
  uint8_t b7
)
{
  uint64_t v0 = (uint64_t)b0;
  uint64_t v1 = (uint64_t)b1 << 8U;
  uint64_t v2 = (uint64_t)b2 << 16U;
  uint64_t v3 = (uint64_t)b3 << 24U;
  uint64_t v4 = (uint64_t)b4 << 32U;
  uint64_t v5 = (uint64_t)b5 << 40U;
  uint64_t v6 = (uint64_t)b6 << 48U;
  uint64_t v7 = (uint64_t)b7 << 56U;
  return v0 | v1 | v2 | v3 | v4 | v5 | v6 | v7;
}

static uint64_t read_word(heap_t h, uint64_t addr)
{
  size_t base = (size_t)addr;
  uint8_t b0 = h.data[base];
  uint8_t b1 = h.data[base + (size_t)1U];
  uint8_t b2 = h.data[base + (size_t)2U];
  uint8_t b3 = h.data[base + (size_t)3U];
  uint8_t b4 = h.data[base + (size_t)4U];
  uint8_t b5 = h.data[base + (size_t)5U];
  uint8_t b6 = h.data[base + (size_t)6U];
  uint8_t b7 = h.data[base + (size_t)7U];
  return combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

static void write_word(heap_t h, uint64_t addr, uint64_t v)
{
  size_t base = (size_t)addr;
  uint8_t b0 = uint64_to_uint8(v);
  uint8_t b1 = uint64_to_uint8(v >> 8U);
  uint8_t b2 = uint64_to_uint8(v >> 16U);
  uint8_t b3 = uint64_to_uint8(v >> 24U);
  uint8_t b4 = uint64_to_uint8(v >> 32U);
  uint8_t b5 = uint64_to_uint8(v >> 40U);
  uint8_t b6 = uint64_to_uint8(v >> 48U);
  uint8_t b7 = uint64_to_uint8(v >> 56U);
  h.data[base] = b0;
  h.data[base + (size_t)1U] = b1;
  h.data[base + (size_t)2U] = b2;
  h.data[base + (size_t)3U] = b3;
  h.data[base + (size_t)4U] = b4;
  h.data[base + (size_t)5U] = b5;
  h.data[base + (size_t)6U] = b6;
  h.data[base + (size_t)7U] = b7;
}

static uint64_t hd_address(uint64_t f_addr)
{
  return f_addr - mword;
}

static uint64_t f_address(uint64_t h_addr)
{
  return h_addr + mword;
}

static GC_Lib_Header_color_sem white = GC_Lib_Header_White;

static GC_Lib_Header_color_sem gray = GC_Lib_Header_Gray;

static GC_Lib_Header_color_sem blue = GC_Lib_Header_Blue;

static GC_Lib_Header_color_sem black = GC_Lib_Header_Black;

static uint64_t no_scan_tag = 251ULL;

static uint64_t getWosize(uint64_t hdr)
{
  return hdr >> 10U;
}

static uint64_t getTag(uint64_t hdr)
{
  return hdr & 0xFFULL;
}

static uint64_t makeHeader(uint64_t wz, GC_Lib_Header_color_sem c, uint64_t t)
{
  uint64_t c_num;
  switch (c)
  {
    case GC_Lib_Header_White:
      {
        c_num = 0ULL;
        break;
      }
    case GC_Lib_Header_Gray:
      {
        c_num = 1ULL;
        break;
      }
    case GC_Lib_Header_Blue:
      {
        c_num = 2ULL;
        break;
      }
    case GC_Lib_Header_Black:
      {
        c_num = 3ULL;
        break;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
  uint64_t wz_shifted = wz << 10U;
  uint64_t c_shifted = c_num << 8U;
  return wz_shifted | c_shifted | t;
}

static uint64_t field_address_pure(uint64_t h_addr, uint64_t i)
{
  uint64_t offset = i * mword;
  return h_addr + offset;
}

static uint64_t read_field(heap_t heap, uint64_t h_addr, uint64_t i)
{
  uint64_t addr = field_address_pure(h_addr, i);
  uint64_t addr_hp = addr;
  return read_word(heap, addr_hp);
}

static bool is_pointer(uint64_t v)
{
  if (v == 0ULL)
    return false;
  else if (v >= heap_size_u64)
    return false;
  else
  {
    uint64_t rem = v % mword;
    return rem == 0ULL;
  }
}

static bool is_empty(gray_stack_rec st)
{
  size_t top_val = *st.top;
  return top_val == st.cap;
}

static bool is_full(gray_stack_rec st)
{
  size_t top_val = *st.top;
  return top_val == (size_t)0U;
}

static void push(gray_stack_rec st, uint64_t addr)
{
  size_t top_val = *st.top;
  size_t new_top = top_val - (size_t)1U;
  st.storage[new_top] = addr;
  *st.top = new_top;
}

static uint64_t pop(gray_stack_rec st)
{
  size_t top_val = *st.top;
  uint64_t v_raw = st.storage[top_val];
  size_t new_top = top_val + (size_t)1U;
  *st.top = new_top;
  return v_raw;
}

static void darken_write_gray(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t new_hdr = makeHeader(getWosize(hdr), gray, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
}

static void darken_if_white_bounded(heap_t heap, gray_stack_rec st, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t raw = hdr >> 8U & 3ULL;
  GC_Lib_Header_color_sem c;
  if (raw == 0ULL)
    c = GC_Lib_Header_White;
  else if (raw == 1ULL)
    c = GC_Lib_Header_Gray;
  else if (raw == 2ULL)
    c = GC_Lib_Header_Blue;
  else
    c = GC_Lib_Header_Black;
  uint64_t obj = f_address(h_addr);
  if (c == white)
  {
    darken_write_gray(heap, h_addr);
    bool full = is_full(st);
    if (!full)
      push(st, obj);
  }
}

static void check_and_darken_bounded(heap_t heap, gray_stack_rec st, uint64_t v)
{
  bool is_ptr = is_pointer(v);
  if (is_ptr)
  {
    uint64_t target_hdr_raw = v - mword;
    uint64_t target_hdr = target_hdr_raw;
    darken_if_white_bounded(heap, st, target_hdr);
  }
}

static void
push_step_body_bounded(heap_t heap, gray_stack_rec st, uint64_t h_addr, uint64_t curr_i)
{
  uint64_t v = read_field(heap, h_addr, curr_i);
  check_and_darken_bounded(heap, st, v);
}

static void
push_children_bounded_impl(heap_t heap, gray_stack_rec st, uint64_t h_addr, uint64_t wz)
{
  uint64_t obj = f_address(h_addr);
  KRML_MAYBE_UNUSED_VAR(obj);
  uint64_t i = 1ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 <= wz;
  while (cond)
  {
    uint64_t curr_i = i;
    push_step_body_bounded(heap, st, h_addr, curr_i);
    i = curr_i + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 <= wz;
  }
}

static void mark_write_black(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t new_hdr = makeHeader(getWosize(hdr), black, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
}

static K___uint64_t_uint64_t mark_read_header(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t wz = getWosize(hdr);
  uint64_t tag = getTag(hdr);
  return ((K___uint64_t_uint64_t){ .fst = wz, .snd = tag });
}

static uint64_t fst__uint64_t_uint64_t(K___uint64_t_uint64_t x)
{
  return x.fst;
}

static uint64_t snd__uint64_t_uint64_t(K___uint64_t_uint64_t x)
{
  return x.snd;
}

static void mark_step_bounded_impl(heap_t heap, gray_stack_rec st)
{
  uint64_t f_addr = pop(st);
  uint64_t h_addr_raw = f_addr - mword;
  uint64_t h_addr = h_addr_raw;
  K___uint64_t_uint64_t r = mark_read_header(heap, h_addr);
  uint64_t wz = fst__uint64_t_uint64_t(r);
  uint64_t tag = snd__uint64_t_uint64_t(r);
  mark_write_black(heap, h_addr);
  if (!(tag >= no_scan_tag))
    push_children_bounded_impl(heap, st, h_addr, wz);
}

static void mark_inner_loop_impl(heap_t heap, gray_stack_rec st)
{
  bool go = true;
  while (go)
  {
    bool empty = is_empty(st);
    if (empty)
      go = false;
    else
      mark_step_bounded_impl(heap, st);
  }
}

static bool is_gray_check(heap_t heap, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t raw = hdr >> 8U & 3ULL;
  GC_Lib_Header_color_sem c;
  if (raw == 0ULL)
    c = GC_Lib_Header_White;
  else if (raw == 1ULL)
    c = GC_Lib_Header_Gray;
  else if (raw == 2ULL)
    c = GC_Lib_Header_Blue;
  else
    c = GC_Lib_Header_Black;
  uint64_t obj = f_address(h_addr);
  KRML_MAYBE_UNUSED_VAR(obj);
  return c == gray;
}

static void rescan_push_if_gray(heap_t heap, gray_stack_rec st, uint64_t h_addr)
{
  bool b = is_gray_check(heap, h_addr);
  if (b)
  {
    bool full = is_full(st);
    if (!full)
    {
      uint64_t obj = f_address(h_addr);
      push(st, obj);
    }
  }
}

static void rescan_heap_impl(heap_t heap, gray_stack_rec st)
{
  uint64_t heap_sz = heap_size_u64;
  uint64_t current = 0ULL;
  uint64_t v0 = current;
  bool cond = v0 + mword < heap_sz;
  while (cond)
  {
    uint64_t v = current;
    uint64_t hdr = read_word(heap, v);
    uint64_t wz = getWosize(hdr);
    rescan_push_if_gray(heap, st, v);
    uint64_t skip = 1ULL + wz;
    uint64_t offset = skip * mword;
    uint64_t next = v + offset;
    current = next;
    uint64_t v0 = current;
    cond = v0 + mword < heap_sz;
  }
}

static void mark_loop_bounded(heap_t heap, gray_stack_rec st)
{
  mark_inner_loop_impl(heap, st);
  bool go = true;
  while (go)
  {
    rescan_heap_impl(heap, st);
    bool empty = is_empty(st);
    if (empty)
      go = false;
    else
      mark_inner_loop_impl(heap, st);
  }
}

static void flush_blue_write_header(heap_t heap, uint64_t fb, uint64_t rw)
{
  uint64_t hd = fb - mword;
  uint64_t wz = rw - 1ULL;
  uint64_t hdr = makeHeader(wz, blue, 0ULL);
  write_word(heap, hd, hdr);
}

static void flush_blue_write_link(heap_t heap, uint64_t fb, uint64_t fp)
{
  write_word(heap, fb, fp);
}

static void zero_fields_loop(heap_t heap, uint64_t start_addr, uint64_t n)
{
  uint64_t idx = 0ULL;
  uint64_t addr = start_addr;
  uint64_t __anf0 = idx;
  bool cond = __anf0 < n;
  while (cond)
  {
    uint64_t cur_a = addr;
    uint64_t cur_i = idx;
    write_word(heap, cur_a, 0ULL);
    uint64_t next_a = cur_a + mword;
    uint64_t next_i = cur_i + 1ULL;
    addr = next_a;
    idx = next_i;
    uint64_t __anf0 = idx;
    cond = __anf0 < n;
  }
}

static K___uint64_t_uint64_t
flush_blue_impl(heap_t heap, uint64_t fb, uint64_t rw, uint64_t fp)
{
  if (rw == 0ULL)
    return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fp });
  else
  {
    flush_blue_write_header(heap, fb, rw);
    uint64_t wz = rw - 1ULL;
    if (wz > 0ULL)
    {
      flush_blue_write_link(heap, fb, fp);
      if (wz > 1ULL)
      {
        uint64_t zero_start = fb + mword;
        uint64_t n_zero = wz - 1ULL;
        zero_fields_loop(heap, zero_start, n_zero);
        return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fb });
      }
      else
        return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fb });
    }
    else
      return ((K___uint64_t_uint64_t){ .fst = 0ULL, .snd = fp });
  }
}

static uint64_t fused_sweep_coalesce(heap_t heap)
{
  uint64_t current = zero_addr;
  uint64_t fb_ref = 0ULL;
  uint64_t rw_ref = 0ULL;
  uint64_t fp_ref = 0ULL;
  uint64_t __anf0 = current;
  bool cond = __anf0 + mword < heap_size_u64;
  while (cond)
  {
    uint64_t cur = current;
    uint64_t cur_fb = fb_ref;
    uint64_t cur_rw = rw_ref;
    uint64_t cur_fv = fp_ref;
    uint64_t hdr = read_word(heap, cur);
    uint64_t wz = getWosize(hdr);
    uint64_t obj = cur + 8ULL;
    uint64_t ws_plus_1 = wz + 1ULL;
    uint64_t offset = ws_plus_1 * mword;
    uint64_t next = cur + offset;
    uint64_t raw = hdr >> 8U & 3ULL;
    GC_Lib_Header_color_sem clr;
    if (raw == 0ULL)
      clr = GC_Lib_Header_White;
    else if (raw == 1ULL)
      clr = GC_Lib_Header_Gray;
    else if (raw == 2ULL)
      clr = GC_Lib_Header_Blue;
    else
      clr = GC_Lib_Header_Black;
    if (GC_Lib_Header_uu___is_Black(clr))
    {
      K___uint64_t_uint64_t res = flush_blue_impl(heap, cur_fb, cur_rw, cur_fv);
      uint64_t new_rw = fst__uint64_t_uint64_t(res);
      uint64_t new_fv = snd__uint64_t_uint64_t(res);
      uint64_t white_hdr = makeHeader(wz, GC_Lib_Header_White, getTag(hdr));
      write_word(heap, cur, white_hdr);
      current = next;
      fb_ref = 0ULL;
      rw_ref = new_rw;
      fp_ref = new_fv;
    }
    else
    {
      uint64_t new_fb;
      if (cur_rw == 0ULL)
        new_fb = obj;
      else
        new_fb = cur_fb;
      uint64_t new_rw = cur_rw + ws_plus_1;
      current = next;
      fb_ref = new_fb;
      rw_ref = new_rw;
    }
    uint64_t __anf0 = current;
    cond = __anf0 + mword < heap_size_u64;
  }
  uint64_t final_fb = fb_ref;
  uint64_t final_rw = rw_ref;
  uint64_t final_fv = fp_ref;
  K___uint64_t_uint64_t res = flush_blue_impl(heap, final_fb, final_rw, final_fv);
  return snd__uint64_t_uint64_t(res);
}

uint64_t collect(heap_t heap, gray_stack_rec st, uint64_t fp)
{
  KRML_MAYBE_UNUSED_VAR(fp);
  mark_loop_bounded(heap, st);
  return fused_sweep_coalesce(heap);
}

static bool is_valid_fp(uint64_t v)
{
  return v >= mword && v < heap_size_u64 && v % mword == 0ULL;
}

uint64_t init_heap(heap_t heap)
{
  uint64_t total_words = heap_size_u64 / mword;
  if (total_words < 2ULL)
    return 0ULL;
  else
  {
    uint64_t wz = total_words - 1ULL;
    uint64_t hdr = makeHeader(wz, blue, 0ULL);
    write_word(heap, zero_addr, hdr);
    write_word(heap, mword, 0ULL);
    return mword;
  }
}

K___uint64_t_uint64_t allocate(heap_t heap, uint64_t fp, uint64_t wosize)
{
  uint64_t wz;
  if (wosize == 0ULL)
    wz = 1ULL;
  else
    wz = wosize;
  uint64_t head_fp = fp;
  uint64_t prev_fp = 0ULL;
  uint64_t cur_fp = fp;
  uint64_t result_obj = 0ULL;
  bool go = true;
  uint64_t fuel_ref = heap_size_u64 / mword;
  while (go)
  {
    uint64_t vfuel = fuel_ref;
    if (vfuel == 0ULL)
      go = false;
    else
    {
      uint64_t vcur = cur_fp;
      bool valid = is_valid_fp(vcur);
      if (!valid)
        go = false;
      else
      {
        uint64_t hd_addr = hd_address(vcur);
        uint64_t hdr = read_word(heap, hd_addr);
        uint64_t block_wz = getWosize(hdr);
        uint64_t next = read_word(heap, vcur);
        if (block_wz >= wz)
        {
          uint64_t leftover = block_wz - wz;
          uint64_t vp = prev_fp;
          if (leftover >= 2ULL)
          {
            uint64_t wz_plus_1 = wz + 1ULL;
            uint64_t offset = wz_plus_1 * mword;
            uint64_t rem_hd_off = hd_addr + offset;
            if (rem_hd_off >= heap_size_u64)
            {
              uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
              write_word(heap, hd_addr, alloc_hdr);
              if (vp == 0ULL)
              {
                head_fp = next;
                result_obj = vcur;
                go = false;
              }
              else
              {
                write_word(heap, vp, next);
                result_obj = vcur;
                go = false;
              }
            }
            else
            {
              uint64_t rem_obj = rem_hd_off + mword;
              if (rem_obj >= heap_size_u64)
              {
                uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
                write_word(heap, hd_addr, alloc_hdr);
                uint64_t rem_wz_u = leftover - 1ULL;
                uint64_t rem_hdr = makeHeader(rem_wz_u, blue, 0ULL);
                write_word(heap, rem_hd_off, rem_hdr);
                if (vp == 0ULL)
                {
                  head_fp = rem_obj;
                  result_obj = vcur;
                  go = false;
                }
                else
                {
                  write_word(heap, vp, rem_obj);
                  result_obj = vcur;
                  go = false;
                }
              }
              else
              {
                uint64_t alloc_hdr = makeHeader(wz, white, 0ULL);
                write_word(heap, hd_addr, alloc_hdr);
                uint64_t rem_wz_u = leftover - 1ULL;
                uint64_t rem_hdr = makeHeader(rem_wz_u, blue, 0ULL);
                write_word(heap, rem_hd_off, rem_hdr);
                write_word(heap, rem_obj, next);
                if (vp == 0ULL)
                {
                  head_fp = rem_obj;
                  result_obj = vcur;
                  go = false;
                }
                else
                {
                  write_word(heap, vp, rem_obj);
                  result_obj = vcur;
                  go = false;
                }
              }
            }
          }
          else
          {
            uint64_t alloc_hdr = makeHeader(block_wz, white, 0ULL);
            write_word(heap, hd_addr, alloc_hdr);
            if (vp == 0ULL)
            {
              head_fp = next;
              result_obj = vcur;
              go = false;
            }
            else
            {
              write_word(heap, vp, next);
              result_obj = vcur;
              go = false;
            }
          }
        }
        else
        {
          prev_fp = vcur;
          cur_fp = next;
          fuel_ref = vfuel - 1ULL;
        }
      }
    }
  }
  uint64_t final_fp = head_fp;
  uint64_t final_obj = result_obj;
  return ((K___uint64_t_uint64_t){ .fst = final_fp, .snd = final_obj });
}

