/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -library Pulse.Spec.GC.Base -library Pulse.Spec.GC.Heap -library Pulse.Spec.GC.Object -library Pulse.Lib.Header -library Pulse.Lib.Address -bundle Pulse.Lib.GC=Pulse.Lib.GC.*,Pulse.Lib.LinkedList -bundle Pulse.Spec.GC.*,Pulse.Lib.Header,Pulse.Lib.Address -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack -no-prefix Pulse.Lib.LinkedList -warn-error -2-9-15 _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Sweep.krml _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/Pulse_Lib_LinkedList.krml _output/FStar_Pervasives_Native.krml _output/Pulse_Spec_GC_Base.krml _output/Pulse_Spec_GC_Heap.krml _output/Pulse_Spec_GC_Object.krml _output/Pulse_Lib_Header.krml _output/Pulse_Lib_Address.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "krmlinit.h"

#include "internal/Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address.h"
#include "internal/Pulse_Lib_GC.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void)
{
  mword = Pulse_Spec_GC_Base_mword;
  heap_size = Pulse_Spec_GC_Base_heap_size;
  zero_addr = Pulse_Spec_GC_Base_zero_addr;
}

