/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -library GC.Spec.Base -library GC.Spec.Heap -library GC.Spec.Object -library GC.Lib.Header -library GC.Lib.Address -bundle GC.Impl=GC.Impl.* -bundle FStar.Pervasives.Native -bundle GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Impl -no-prefix GC.Impl.Mark -no-prefix GC.Impl.Sweep -no-prefix GC.Impl.Fields -no-prefix GC.Impl.Closure -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -warn-error -2-9-15 _output/GC_Impl_Fields.krml _output/GC_Impl_Closure.krml _output/GC_Impl_Mark.krml _output/GC_Impl_Sweep.krml _output/GC_Impl.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/FStar_Pervasives_Native.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef krmlinit_H
#define krmlinit_H

#include "krmllib.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void);


#define krmlinit_H_DEFINED
#endif /* krmlinit_H */
