/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: ../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -library Pulse.Spec.GC.Base -library Pulse.Spec.GC.Heap -library Pulse.Spec.GC.Object -library Pulse.Lib.Header -library Pulse.Lib.Address -bundle Pulse.Lib.GC=Pulse.Lib.GC.* -bundle FStar.Pervasives.Native -bundle Pulse.Spec.GC.*,Pulse.Lib.Header,Pulse.Lib.Address -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack -warn-error -2-9-15 _output/FStar_Pervasives_Native.krml _output/Pulse_Lib_Address.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/Pulse_Lib_GC_Sweep.krml _output/Pulse_Lib_Header.krml _output/Pulse_Spec_GC_Base.krml _output/Pulse_Spec_GC_Heap.krml _output/Pulse_Spec_GC_Object.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef Pulse_Lib_GC_H
#define Pulse_Lib_GC_H

#include "krmllib.h"

typedef struct heap_t_s
{
  uint8_t *data;
  size_t size;
}
heap_t;

typedef struct gray_stack_rec_s
{
  uint64_t *storage;
  size_t *top;
  size_t cap;
}
gray_stack_rec;

uint64_t collect(heap_t heap, gray_stack_rec st, uint64_t fp);


#define Pulse_Lib_GC_H_DEFINED
#endif /* Pulse_Lib_GC_H */
