/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -warn-error -2-9-11-15-17 -bundle Pulse.Lib.GC+Pulse.Lib.GC.Mark+Pulse.Lib.GC.Sweep+Pulse.Lib.GC.Fields+Pulse.Lib.GC.Closure+Pulse.Lib.GC.Heap+Pulse.Lib.GC.Object+Pulse.Lib.GC.Stack=Pulse.Lib.GC.*[rename=PulseGC] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/Pulse_Lib_GC_Sweep.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "PulseGC.h"

#include "internal/FStar_Pulse_PulseCore_Prims.h"

void write_word_ex(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t v)
{
  write_word(heap, h_addr, v);
}

uint64_t
sweep_white_spec(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp)
{
  if (wz > 0ULL)
  {
    Pulse_Spec_GC_Base_obj_addr obj = Pulse_Spec_GC_Heap_f_address(h_addr);
    KRML_MAYBE_UNUSED_VAR(obj);
    Pulse_Spec_GC_Base_hp_addr field1_addr = field1_of(h_addr);
    write_word(heap, field1_addr, fp);
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t blue_hdr = makeHeader(getWosize(hdr), blue, getTag(hdr));
    write_word(heap, h_addr, blue_hdr);
    return Pulse_Spec_GC_Heap_f_address(h_addr);
  }
  else
  {
    Pulse_Spec_GC_Base_obj_addr obj = Pulse_Spec_GC_Heap_f_address(h_addr);
    KRML_MAYBE_UNUSED_VAR(obj);
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t blue_hdr = makeHeader(getWosize(hdr), blue, getTag(hdr));
    write_word(heap, h_addr, blue_hdr);
    return Pulse_Spec_GC_Heap_f_address(h_addr);
  }
}

uint64_t
sweep_black_spec(
  heap_t heap,
  Pulse_Spec_GC_Base_hp_addr h_addr,
  uint64_t wz,
  uint64_t hdr,
  uint64_t fp
)
{
  uint64_t new_hdr = makeHeader(wz, white, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
  return fp;
}

uint64_t
sweep_white_case(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp)
{
  return sweep_white_spec(heap, h_addr, wz, fp);
}

uint64_t
sweep_black_case(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp)
{
  uint64_t hdr = read_word(heap, h_addr);
  sweep_black_spec(heap, h_addr, wz, hdr, fp);
  return fp;
}

uint64_t sweep_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp)
{
  uint64_t hdr = read_word(heap, h_addr);
  Pulse_Lib_Header_color_sem color = getColor(hdr);
  if (__eq__Pulse_Lib_Header_color_sem(color, white))
    return sweep_white_case(heap, h_addr, wz, fp);
  else if (__eq__Pulse_Lib_Header_color_sem(color, black))
    return sweep_black_case(heap, h_addr, wz, fp);
  else
    return fp;
}

krml_checked_int_t spec_field_address(krml_checked_int_t h_addr, krml_checked_int_t i)
{
  return Prims_op_Addition(h_addr, Prims_op_Multiply(i, (krml_checked_int_t)8));
}

uint64_t field_address(Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t i)
{
  return field_address_pure(h_addr, i);
}

uint64_t read_succ(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t i)
{
  return read_field(heap, h_addr, i, (void *)0U);
}

bool is_pointer(uint64_t v)
{
  if (v == 0ULL)
    return false;
  else if (v >= FStar_UInt64_uint_to_t(heap_size))
    return false;
  else
  {
    uint64_t rem = v % mword;
    return rem == 0ULL;
  }
}

void
for_each_successor(
  heap_t heap,
  Pulse_Spec_GC_Base_hp_addr h_addr,
  uint64_t wz,
  void (*callback)(uint64_t x0)
)
{
  uint64_t i = 1ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 <= wz;
  while (cond)
  {
    uint64_t curr_i = i;
    uint64_t v = read_field(heap, h_addr, curr_i, (void *)0U);
    bool is_ptr = is_pointer(v);
    if (is_ptr)
      callback(v);
    Pulse_Lib_Reference_replace(&i, curr_i + 1ULL, (void *)0U);
    uint64_t __anf0 = i;
    cond = __anf0 <= wz;
  }
}

uint64_t closinfo_val(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr)
{
  return read_field(heap, h_addr, 2ULL, (void *)0U);
}

uint64_t start_env_from_closinfo(uint64_t closinfo)
{
  return closinfo >> 32U;
}

bool is_infix_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t t = getTag(hdr);
  return t == infix_tag;
}

bool is_closure_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t t = getTag(hdr);
  return t == closure_tag;
}

Pulse_Spec_GC_Base_hp_addr resolve_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr obj)
{
  bool is_infix = is_infix_object(heap, obj);
  if (is_infix)
    return parent_closure_of_infix(heap, obj);
  else
    return obj;
}

void
scan_closure_env(
  heap_t heap,
  Pulse_Spec_GC_Base_hp_addr h_addr,
  uint64_t wz,
  void (*callback)(uint64_t x0)
)
{
  uint64_t closinfo = closinfo_val(heap, h_addr);
  uint64_t start_env_raw = start_env_from_closinfo(closinfo);
  uint64_t start_env;
  if (start_env_raw < 1ULL)
    start_env = 1ULL;
  else
    start_env = start_env_raw;
  uint64_t wz_u64 = wz;
  uint64_t start_env_clamped;
  if (start_env > wz_u64)
    start_env_clamped = wz_u64;
  else
    start_env_clamped = start_env;
  uint64_t i = start_env_clamped;
  uint64_t __anf0 = i;
  bool cond = __anf0 <= wz;
  while (cond)
  {
    uint64_t curr_i = i;
    uint64_t v = read_field(heap, h_addr, curr_i, (void *)0U);
    bool is_ptr = is_pointer(v);
    if (is_ptr)
      callback(v);
    i = curr_i + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 <= wz;
  }
}

bool is_no_scan(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t t = getTag(hdr);
  return t >= no_scan_tag;
}

uint64_t mword;

krml_checked_int_t heap_size;

size_t heap_size_sz;

Pulse_Spec_GC_Base_hp_addr zero_addr;

uint64_t uint8_to_uint64(uint8_t x)
{
  return Pulse_Spec_GC_Heap_uint8_to_uint64(x);
}

uint8_t uint64_to_uint8(uint64_t x)
{
  return Pulse_Spec_GC_Heap_uint64_to_uint8(x);
}

uint64_t
combine_bytes(
  uint8_t b0,
  uint8_t b1,
  uint8_t b2,
  uint8_t b3,
  uint8_t b4,
  uint8_t b5,
  uint8_t b6,
  uint8_t b7
)
{
  return Pulse_Spec_GC_Heap_combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

uint64_t spec_read_word(Pulse_Spec_GC_Base_heap s, krml_checked_int_t addr)
{
  return
    combine_bytes(FStar_Seq_Base_index(s, addr),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)1)),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)2)),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)3)),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)4)),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)5)),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)6)),
      FStar_Seq_Base_index(s, Prims_op_Addition(addr, (krml_checked_int_t)7)));
}

uint8_t read_byte(heap_t h, uint64_t addr)
{
  size_t idx = (size_t)addr;
  return h.data[idx];
}

uint64_t read_word(heap_t h, Pulse_Spec_GC_Base_hp_addr addr)
{
  size_t base = (size_t)addr;
  uint8_t b0 = h.data[base];
  uint8_t b1 = h.data[base + (size_t)1U];
  uint8_t b2 = h.data[base + (size_t)2U];
  uint8_t b3 = h.data[base + (size_t)3U];
  uint8_t b4 = h.data[base + (size_t)4U];
  uint8_t b5 = h.data[base + (size_t)5U];
  uint8_t b6 = h.data[base + (size_t)6U];
  uint8_t b7 = h.data[base + (size_t)7U];
  return combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

void write_byte(heap_t h, uint64_t addr, uint8_t v)
{
  size_t idx = (size_t)addr;
  h.data[idx] = v;
}

void write_word(heap_t h, Pulse_Spec_GC_Base_hp_addr addr, uint64_t v)
{
  size_t base = (size_t)addr;
  uint8_t b0 = uint64_to_uint8(v);
  uint8_t b1 = uint64_to_uint8(v >> 8U);
  uint8_t b2 = uint64_to_uint8(v >> 16U);
  uint8_t b3 = uint64_to_uint8(v >> 24U);
  uint8_t b4 = uint64_to_uint8(v >> 32U);
  uint8_t b5 = uint64_to_uint8(v >> 40U);
  uint8_t b6 = uint64_to_uint8(v >> 48U);
  uint8_t b7 = uint64_to_uint8(v >> 56U);
  h.data[base] = b0;
  h.data[base + (size_t)1U] = b1;
  h.data[base + (size_t)2U] = b2;
  h.data[base + (size_t)3U] = b3;
  h.data[base + (size_t)4U] = b4;
  h.data[base + (size_t)5U] = b5;
  h.data[base + (size_t)6U] = b6;
  h.data[base + (size_t)7U] = b7;
}

heap_t alloc_heap(void)
{
  KRML_CHECK_SIZE(sizeof (uint8_t), heap_size_sz);
  uint8_t data[heap_size_sz];
  memset(data, 0U, heap_size_sz * sizeof (uint8_t));
  return ((heap_t){ .data = data, .size = heap_size_sz });
}

bool is_word_aligned(uint64_t addr)
{
  return addr % mword == 0ULL;
}

uint64_t pack_color(Pulse_Lib_Header_color_sem c)
{
  return FStar_UInt64_uint_to_t(Pulse_Lib_Header_pack_color(c));
}

uint64_t closure_tag = 247ULL;

uint64_t infix_tag = 249ULL;

uint64_t no_scan_tag = 251ULL;

uint64_t getWosize(uint64_t hdr)
{
  return hdr >> 10U;
}

uint64_t getTag(uint64_t hdr)
{
  return hdr & 0xFFULL;
}

uint64_t makeHeader(uint64_t wz, Pulse_Lib_Header_color_sem c, uint64_t t)
{
  uint64_t c_num = pack_color(c);
  uint64_t wz_shifted = wz << 10U;
  uint64_t c_shifted = c_num << 8U;
  return wz_shifted | c_shifted | t;
}

Pulse_Lib_Header_color_sem color_of_object(uint64_t hdr)
{
  return getColor(hdr);
}

bool is_white_object(uint64_t hdr)
{
  return __eq__Pulse_Lib_Header_color_sem(getColor(hdr), white);
}

bool is_gray_object(uint64_t hdr)
{
  return __eq__Pulse_Lib_Header_color_sem(getColor(hdr), gray);
}

bool is_black_object(uint64_t hdr)
{
  return __eq__Pulse_Lib_Header_color_sem(getColor(hdr), black);
}

void
colorHeader(heap_t heap, Pulse_Spec_GC_Base_hp_addr h, Pulse_Lib_Header_color_sem new_color)
{
  uint64_t hdr = read_word(heap, h);
  uint64_t wz = getWosize(hdr);
  uint64_t t = getTag(hdr);
  uint64_t new_hdr = makeHeader(wz, new_color, t);
  write_word(heap, h, new_hdr);
}

bool isPointer(uint64_t v)
{
  return
    Prims_op_GreaterThanOrEqual(FStar_UInt64_v(v), FStar_UInt64_v(mword)) &&
      Prims_op_LessThan(FStar_UInt64_v(v),
        heap_size)
    && Prims_op_Modulus(FStar_UInt64_v(v), FStar_UInt64_v(mword)) == (krml_checked_int_t)0;
}

Pulse_Lib_Header_color_sem (*get_color)(uint64_t x0) = color_of_object;

uint64_t (*get_wosize)(uint64_t x0) = getWosize;

uint64_t (*get_tag)(uint64_t x0) = getTag;

bool (*is_black)(uint64_t x0) = is_black_object;

bool (*is_white)(uint64_t x0) = is_white_object;

bool (*is_gray)(uint64_t x0) = is_gray_object;

