/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -library Pulse.Spec.GC.Base -library Pulse.Spec.GC.Heap -library Pulse.Spec.GC.Object -library Pulse.Lib.Header -library Pulse.Lib.Address -bundle Pulse.Lib.GC=Pulse.Lib.GC.* -bundle FStar.Pervasives.Native -bundle Pulse.Spec.GC.*,Pulse.Lib.Header,Pulse.Lib.Address -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack -warn-error -2-9-15 _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Sweep.krml _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/FStar_Pervasives_Native.krml _output/Pulse_Spec_GC_Base.krml _output/Pulse_Spec_GC_Heap.krml _output/Pulse_Spec_GC_Object.krml _output/Pulse_Lib_Header.krml _output/Pulse_Lib_Address.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/Pulse_Lib_GC.h"

#include "internal/Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address.h"
#include "pulsegc_compat.h"

uint64_t mword;

krml_checked_int_t heap_size;

uint64_t heap_size_u64;

uint64_t zero_addr;

static uint8_t uint64_to_uint8(uint64_t x)
{
  return Pulse_Spec_GC_Heap_uint64_to_uint8(x);
}

static uint64_t
combine_bytes(
  uint8_t b0,
  uint8_t b1,
  uint8_t b2,
  uint8_t b3,
  uint8_t b4,
  uint8_t b5,
  uint8_t b6,
  uint8_t b7
)
{
  return Pulse_Spec_GC_Heap_combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

static uint64_t read_word(heap_t h, uint64_t addr)
{
  size_t base = (size_t)addr;
  uint8_t b0 = h.data[base];
  uint8_t b1 = h.data[base + (size_t)1U];
  uint8_t b2 = h.data[base + (size_t)2U];
  uint8_t b3 = h.data[base + (size_t)3U];
  uint8_t b4 = h.data[base + (size_t)4U];
  uint8_t b5 = h.data[base + (size_t)5U];
  uint8_t b6 = h.data[base + (size_t)6U];
  uint8_t b7 = h.data[base + (size_t)7U];
  return combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

static void write_word(heap_t h, uint64_t addr, uint64_t v)
{
  size_t base = (size_t)addr;
  uint8_t b0 = uint64_to_uint8(v);
  uint8_t b1 = uint64_to_uint8(v >> 8U);
  uint8_t b2 = uint64_to_uint8(v >> 16U);
  uint8_t b3 = uint64_to_uint8(v >> 24U);
  uint8_t b4 = uint64_to_uint8(v >> 32U);
  uint8_t b5 = uint64_to_uint8(v >> 40U);
  uint8_t b6 = uint64_to_uint8(v >> 48U);
  uint8_t b7 = uint64_to_uint8(v >> 56U);
  h.data[base] = b0;
  h.data[base + (size_t)1U] = b1;
  h.data[base + (size_t)2U] = b2;
  h.data[base + (size_t)3U] = b3;
  h.data[base + (size_t)4U] = b4;
  h.data[base + (size_t)5U] = b5;
  h.data[base + (size_t)6U] = b6;
  h.data[base + (size_t)7U] = b7;
}

static uint64_t f_address(uint64_t h_addr)
{
  return h_addr + mword;
}

static Pulse_Lib_Header_color_sem white = Pulse_Lib_Header_White;

static Pulse_Lib_Header_color_sem blue = Pulse_Lib_Header_Blue;

static Pulse_Lib_Header_color_sem black = Pulse_Lib_Header_Black;

static uint64_t no_scan_tag = 251ULL;

static uint64_t getWosize(uint64_t hdr)
{
  return hdr >> 10U;
}

static uint64_t getTag(uint64_t hdr)
{
  return hdr & 0xFFULL;
}

static uint64_t makeHeader(uint64_t wz, Pulse_Lib_Header_color_sem c, uint64_t t)
{
  uint64_t c_num;
  switch (c)
  {
    case Pulse_Lib_Header_White:
      {
        c_num = 0ULL;
        break;
      }
    case Pulse_Lib_Header_Gray:
      {
        c_num = 1ULL;
        break;
      }
    case Pulse_Lib_Header_Blue:
      {
        c_num = 2ULL;
        break;
      }
    case Pulse_Lib_Header_Black:
      {
        c_num = 3ULL;
        break;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
  uint64_t wz_shifted = wz << 10U;
  uint64_t c_shifted = c_num << 8U;
  return wz_shifted | c_shifted | t;
}

static uint64_t field_address_pure(uint64_t h_addr, uint64_t i)
{
  uint64_t offset = i * mword;
  return h_addr + offset;
}

static uint64_t read_field(heap_t heap, uint64_t h_addr, uint64_t i)
{
  uint64_t addr = field_address_pure(h_addr, i);
  uint64_t addr_hp = addr;
  return read_word(heap, addr_hp);
}

static bool is_pointer(uint64_t v)
{
  if (v == 0ULL)
    return false;
  else if (v >= heap_size_u64)
    return false;
  else
  {
    uint64_t rem = v % mword;
    return rem == 0ULL;
  }
}

static bool is_empty(gray_stack_rec st)
{
  size_t top_val = *st.top;
  return top_val == st.cap;
}

static void push(gray_stack_rec st, uint64_t addr)
{
  size_t top_val = *st.top;
  size_t new_top = top_val - (size_t)1U;
  st.storage[new_top] = addr;
  *st.top = new_top;
}

static uint64_t pop(gray_stack_rec st)
{
  size_t top_val = *st.top;
  uint64_t v_raw = st.storage[top_val];
  size_t new_top = top_val + (size_t)1U;
  *st.top = new_top;
  return v_raw;
}

static void darken_if_white(heap_t heap, gray_stack_rec st, uint64_t h_addr)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t raw = hdr >> 8U & 3ULL;
  Pulse_Lib_Header_color_sem c;
  if (raw == 0ULL)
    c = Pulse_Lib_Header_White;
  else if (raw == 1ULL)
    c = Pulse_Lib_Header_Gray;
  else if (raw == 2ULL)
    c = Pulse_Lib_Header_Blue;
  else
    c = Pulse_Lib_Header_Black;
  uint64_t obj = f_address(h_addr);
  if (c == white)
  {
    uint64_t new_hdr = Pulse_Spec_GC_Object_colorHeader(hdr, Pulse_Lib_Header_Gray);
    write_word(heap, h_addr, new_hdr);
    push(st, obj);
  }
}

static void check_and_darken(heap_t heap, gray_stack_rec st, uint64_t v)
{
  bool is_ptr = is_pointer(v);
  if (is_ptr)
  {
    uint64_t target_hdr_raw = v - mword;
    uint64_t target_hdr = target_hdr_raw;
    darken_if_white(heap, st, target_hdr);
  }
}

static void push_step_body(heap_t heap, gray_stack_rec st, uint64_t h_addr, uint64_t curr_i)
{
  uint64_t v = read_field(heap, h_addr, curr_i);
  check_and_darken(heap, st, v);
}

static void push_children(heap_t heap, gray_stack_rec st, uint64_t h_addr, uint64_t wz)
{
  uint64_t obj = f_address(h_addr);
  KRML_MAYBE_UNUSED_VAR(obj);
  uint64_t i = 1ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 <= wz;
  while (cond)
  {
    uint64_t curr_i = i;
    push_step_body(heap, st, h_addr, curr_i);
    i = curr_i + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 <= wz;
  }
}

static void mark_step(heap_t heap, gray_stack_rec st)
{
  uint64_t f_addr = pop(st);
  uint64_t h_addr_raw = f_addr - mword;
  uint64_t h_addr = h_addr_raw;
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t wz = getWosize(hdr);
  uint64_t tag = getTag(hdr);
  uint64_t new_hdr = makeHeader(wz, black, tag);
  write_word(heap, h_addr, new_hdr);
  if (!(tag >= no_scan_tag))
    push_children(heap, st, h_addr, wz);
}

static void mark_loop(heap_t heap, gray_stack_rec st)
{
  uint64_t fuel_init = heap_size_u64 / mword;
  bool go = true;
  uint64_t fuel_ref = fuel_init;
  while (go)
  {
    bool empty = is_empty(st);
    if (empty)
      go = false;
    else
    {
      mark_step(heap, st);
      uint64_t cur_fuel = fuel_ref;
      fuel_ref = cur_fuel - 1ULL;
    }
  }
}

static uint64_t field1_of(uint64_t h_addr)
{
  return h_addr + mword;
}

static uint64_t sweep_white_spec(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  if (wz > 0ULL)
  {
    uint64_t obj = Pulse_Spec_GC_Heap_f_address(h_addr);
    KRML_MAYBE_UNUSED_VAR(obj);
    uint64_t field1_addr = field1_of(h_addr);
    write_word(heap, field1_addr, fp);
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t blue_hdr = makeHeader(getWosize(hdr), blue, getTag(hdr));
    write_word(heap, h_addr, blue_hdr);
    return Pulse_Spec_GC_Heap_f_address(h_addr);
  }
  else
  {
    uint64_t obj = Pulse_Spec_GC_Heap_f_address(h_addr);
    KRML_MAYBE_UNUSED_VAR(obj);
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t blue_hdr = makeHeader(getWosize(hdr), blue, getTag(hdr));
    write_word(heap, h_addr, blue_hdr);
    return Pulse_Spec_GC_Heap_f_address(h_addr);
  }
}

static uint64_t
sweep_black_spec(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t hdr, uint64_t fp)
{
  uint64_t new_hdr = makeHeader(wz, white, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
  return fp;
}

static uint64_t sweep_white_case(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  return sweep_white_spec(heap, h_addr, wz, fp);
}

static uint64_t sweep_black_case(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  uint64_t hdr = read_word(heap, h_addr);
  sweep_black_spec(heap, h_addr, wz, hdr, fp);
  return fp;
}

static uint64_t sweep_object(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t raw = hdr >> 8U & 3ULL;
  Pulse_Lib_Header_color_sem color;
  if (raw == 0ULL)
    color = Pulse_Lib_Header_White;
  else if (raw == 1ULL)
    color = Pulse_Lib_Header_Gray;
  else if (raw == 2ULL)
    color = Pulse_Lib_Header_Blue;
  else
    color = Pulse_Lib_Header_Black;
  if (color == white)
    return sweep_white_case(heap, h_addr, wz, fp);
  else if (color == black)
    return sweep_black_case(heap, h_addr, wz, fp);
  else
    return fp;
}

static uint64_t next_object(uint64_t h_addr, uint64_t wz)
{
  uint64_t skip = 1ULL + wz;
  uint64_t offset = skip * mword;
  return h_addr + offset;
}

static void sweep_loop(heap_t heap, uint64_t *current, uint64_t *free_ptr)
{
  uint64_t __anf0 = *current;
  bool cond = __anf0 + mword < heap_size_u64;
  while (cond)
  {
    uint64_t h_addr_raw = *current;
    uint64_t h_addr = h_addr_raw;
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t wz = getWosize(hdr);
    uint64_t cur_fp = *free_ptr;
    uint64_t new_fp = sweep_object(heap, h_addr, wz, cur_fp);
    *free_ptr = new_fp;
    uint64_t next_addr = next_object(h_addr, wz);
    *current = next_addr;
    uint64_t __anf0 = *current;
    cond = __anf0 + mword < heap_size_u64;
  }
}

static uint64_t sweep(heap_t heap, uint64_t fp)
{
  uint64_t cur_init = zero_addr;
  uint64_t current = cur_init;
  uint64_t free_ptr = fp;
  sweep_loop(heap, &current, &free_ptr);
  return free_ptr;
}

uint64_t collect(heap_t heap, gray_stack_rec st, uint64_t fp)
{
  mark_loop(heap, st);
  return sweep(heap, fp);
}

