/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -warn-error -2-9-11-15-17 -bundle Pulse.Lib.GC+Pulse.Lib.GC.Mark+Pulse.Lib.GC.Sweep+Pulse.Lib.GC.Fields+Pulse.Lib.GC.Closure+Pulse.Lib.GC.Heap+Pulse.Lib.GC.Object+Pulse.Lib.GC.Stack=Pulse.Lib.GC.*[rename=PulseGC] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/Pulse_Lib_GC_Sweep.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef PulseGC_H
#define PulseGC_H

#include "krmllib.h"
#include "PulseGC_compat.h"

typedef struct heap_t_s
{
  uint8_t *data;
  size_t size;
}
heap_t;

void write_word_ex(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t v);

uint64_t
sweep_white_spec(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp);

uint64_t
sweep_black_spec(
  heap_t heap,
  Pulse_Spec_GC_Base_hp_addr h_addr,
  uint64_t wz,
  uint64_t hdr,
  uint64_t fp
);

uint64_t
sweep_white_case(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp);

uint64_t
sweep_black_case(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp);

extern bool
__eq__Pulse_Lib_Header_color_sem(Pulse_Lib_Header_color_sem x, Pulse_Lib_Header_color_sem y);

uint64_t
sweep_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t wz, uint64_t fp);

krml_checked_int_t spec_field_address(krml_checked_int_t h_addr, krml_checked_int_t i);

uint64_t field_address(Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t i);

uint64_t read_succ(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr, uint64_t i);

bool is_pointer(uint64_t v);

void
for_each_successor(
  heap_t heap,
  Pulse_Spec_GC_Base_hp_addr h_addr,
  uint64_t wz,
  void (*callback)(uint64_t x0)
);

uint64_t closinfo_val(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr);

uint64_t start_env_from_closinfo(uint64_t closinfo);

bool is_infix_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr);

bool is_closure_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr);

Pulse_Spec_GC_Base_hp_addr resolve_object(heap_t heap, Pulse_Spec_GC_Base_hp_addr obj);

void
scan_closure_env(
  heap_t heap,
  Pulse_Spec_GC_Base_hp_addr h_addr,
  uint64_t wz,
  void (*callback)(uint64_t x0)
);

bool is_no_scan(heap_t heap, Pulse_Spec_GC_Base_hp_addr h_addr);

extern uint64_t mword;

extern krml_checked_int_t heap_size;

extern size_t heap_size_sz;

typedef Pulse_Spec_GC_Base_hp_addr hp_addr;

extern Pulse_Spec_GC_Base_hp_addr zero_addr;

typedef void *is_hp_addr;

typedef Pulse_Spec_GC_Base_obj_addr obj_addr;

typedef void *is_val_addr;

typedef uint64_t val_addr;

typedef Pulse_Spec_GC_Base_heap heap_state;

uint64_t uint8_to_uint64(uint8_t x);

uint8_t uint64_to_uint8(uint64_t x);

uint64_t
combine_bytes(
  uint8_t b0,
  uint8_t b1,
  uint8_t b2,
  uint8_t b3,
  uint8_t b4,
  uint8_t b5,
  uint8_t b6,
  uint8_t b7
);

uint64_t spec_read_word(Pulse_Spec_GC_Base_heap s, krml_checked_int_t addr);

uint8_t read_byte(heap_t h, uint64_t addr);

uint64_t read_word(heap_t h, Pulse_Spec_GC_Base_hp_addr addr);

void write_byte(heap_t h, uint64_t addr, uint8_t v);

void write_word(heap_t h, Pulse_Spec_GC_Base_hp_addr addr, uint64_t v);

heap_t alloc_heap(void);

bool is_word_aligned(uint64_t addr);

typedef uint64_t wosize;

typedef Pulse_Lib_Header_color_sem color;

typedef uint64_t tag;

uint64_t pack_color(Pulse_Lib_Header_color_sem c);

extern uint64_t closure_tag;

extern uint64_t infix_tag;

extern uint64_t no_scan_tag;

uint64_t getWosize(uint64_t hdr);

uint64_t getTag(uint64_t hdr);

uint64_t makeHeader(uint64_t wz, Pulse_Lib_Header_color_sem c, uint64_t t);

Pulse_Lib_Header_color_sem color_of_object(uint64_t hdr);

bool is_white_object(uint64_t hdr);

bool is_gray_object(uint64_t hdr);

bool is_black_object(uint64_t hdr);

void
colorHeader(heap_t heap, Pulse_Spec_GC_Base_hp_addr h, Pulse_Lib_Header_color_sem new_color);

bool isPointer(uint64_t v);

extern Pulse_Lib_Header_color_sem (*get_color)(uint64_t x0);

extern uint64_t (*get_wosize)(uint64_t x0);

extern uint64_t (*get_tag)(uint64_t x0);

extern bool (*is_black)(uint64_t x0);

extern bool (*is_white)(uint64_t x0);

extern bool (*is_gray)(uint64_t x0);


#define PulseGC_H_DEFINED
#endif /* PulseGC_H */
