/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -library Pulse.Spec.GC.Base -library Pulse.Spec.GC.Heap -library Pulse.Spec.GC.Object -library Pulse.Lib.Header -library Pulse.Lib.Address -bundle Pulse.Lib.GC=Pulse.Lib.GC.*,Pulse.Lib.LinkedList -bundle FStar.Pervasives.Native -bundle Pulse.Spec.GC.*,Pulse.Lib.Header,Pulse.Lib.Address -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack -no-prefix Pulse.Lib.LinkedList -warn-error -2-9-15 _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Sweep.krml _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/Pulse_Lib_LinkedList.krml _output/FStar_Pervasives_Native.krml _output/Pulse_Spec_GC_Base.krml _output/Pulse_Spec_GC_Heap.krml _output/Pulse_Spec_GC_Object.krml _output/Pulse_Lib_Header.krml _output/Pulse_Lib_Address.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#include "internal/Pulse_Lib_GC.h"

#include "Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address.h"
#include "internal/Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address.h"
#include "pulsegc_compat.h"

uint64_t mword;

krml_checked_int_t heap_size;

uint64_t zero_addr;

static uint8_t uint64_to_uint8(uint64_t x)
{
  return Pulse_Spec_GC_Heap_uint64_to_uint8(x);
}

static uint64_t
combine_bytes(
  uint8_t b0,
  uint8_t b1,
  uint8_t b2,
  uint8_t b3,
  uint8_t b4,
  uint8_t b5,
  uint8_t b6,
  uint8_t b7
)
{
  return Pulse_Spec_GC_Heap_combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

static uint64_t read_word(heap_t h, uint64_t addr)
{
  size_t base = (size_t)addr;
  uint8_t b0 = h.data[base];
  uint8_t b1 = h.data[base + (size_t)1U];
  uint8_t b2 = h.data[base + (size_t)2U];
  uint8_t b3 = h.data[base + (size_t)3U];
  uint8_t b4 = h.data[base + (size_t)4U];
  uint8_t b5 = h.data[base + (size_t)5U];
  uint8_t b6 = h.data[base + (size_t)6U];
  uint8_t b7 = h.data[base + (size_t)7U];
  return combine_bytes(b0, b1, b2, b3, b4, b5, b6, b7);
}

static void write_word(heap_t h, uint64_t addr, uint64_t v)
{
  size_t base = (size_t)addr;
  uint8_t b0 = uint64_to_uint8(v);
  uint8_t b1 = uint64_to_uint8(v >> 8U);
  uint8_t b2 = uint64_to_uint8(v >> 16U);
  uint8_t b3 = uint64_to_uint8(v >> 24U);
  uint8_t b4 = uint64_to_uint8(v >> 32U);
  uint8_t b5 = uint64_to_uint8(v >> 40U);
  uint8_t b6 = uint64_to_uint8(v >> 48U);
  uint8_t b7 = uint64_to_uint8(v >> 56U);
  h.data[base] = b0;
  h.data[base + (size_t)1U] = b1;
  h.data[base + (size_t)2U] = b2;
  h.data[base + (size_t)3U] = b3;
  h.data[base + (size_t)4U] = b4;
  h.data[base + (size_t)5U] = b5;
  h.data[base + (size_t)6U] = b6;
  h.data[base + (size_t)7U] = b7;
}

static uint64_t f_address(uint64_t h_addr)
{
  return h_addr + mword;
}

static Pulse_Lib_Header_color_sem white = Pulse_Lib_Header_White;

static Pulse_Lib_Header_color_sem blue = Pulse_Lib_Header_Blue;

static Pulse_Lib_Header_color_sem black = Pulse_Lib_Header_Black;

static uint64_t pack_color(Pulse_Lib_Header_color_sem c)
{
  return FStar_UInt64_uint_to_t(Pulse_Lib_Header_pack_color(c));
}

static uint64_t no_scan_tag = 251ULL;

static uint64_t getWosize(uint64_t hdr)
{
  return hdr >> 10U;
}

static Pulse_Lib_Header_color_sem getColor(uint64_t hdr)
{
  uint64_t raw = hdr >> 8U & 3ULL;
  FStar_Pervasives_Native_option__Pulse_Lib_Header_color_sem
  scrut = Pulse_Lib_Header_unpack_color(FStar_UInt64_v(raw));
  if (scrut.tag == FStar_Pervasives_Native_Some)
    return scrut.v;
  else if (scrut.tag == FStar_Pervasives_Native_None)
    return Pulse_Lib_Header_White;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static uint64_t getTag(uint64_t hdr)
{
  return hdr & 0xFFULL;
}

static uint64_t makeHeader(uint64_t wz, Pulse_Lib_Header_color_sem c, uint64_t t)
{
  uint64_t c_num = pack_color(c);
  uint64_t wz_shifted = wz << 10U;
  uint64_t c_shifted = c_num << 8U;
  return wz_shifted | c_shifted | t;
}

static uint64_t field_address_pure(uint64_t h_addr, uint64_t i)
{
  uint64_t offset = i * mword;
  return h_addr + offset;
}

static uint64_t read_field(heap_t heap, uint64_t h_addr, uint64_t i)
{
  uint64_t addr = field_address_pure(h_addr, i);
  uint64_t addr_hp = addr;
  return read_word(heap, addr_hp);
}

static bool is_pointer(uint64_t v)
{
  if (v == 0ULL)
    return false;
  else if (v >= FStar_UInt64_uint_to_t(heap_size))
    return false;
  else
  {
    uint64_t rem = v % mword;
    return rem == 0ULL;
  }
}

static bool
is_empty__uint64_t(FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ x)
{
  if (x.tag == FStar_Pervasives_Native_None)
    return true;
  else if (x.tag == FStar_Pervasives_Native_Some)
    return false;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static bool is_empty(FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st)
{
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ curr = *st;
  return is_empty__uint64_t(curr);
}

static FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_
cons__uint64_t(
  uint64_t v,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ x
)
{
  node__uint64_t *y = KRML_HOST_MALLOC(sizeof (node__uint64_t));
  if (y != NULL)
    y[0U] = ((node__uint64_t){ .head = v, .tail = x });
  return
    (
      (FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_){
        .tag = FStar_Pervasives_Native_Some,
        .v = y
      }
    );
}

static void
push(FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st, uint64_t addr)
{
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ curr = *st;
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_
  new_ll = cons__uint64_t(addr, curr);
  *st = new_ll;
}

typedef struct
__FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t_s
{
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ fst;
  uint64_t snd;
}
__FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t;

static __FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t
pop__uint64_t(FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ x)
{
  node__uint64_t *np;
  if (x.tag == FStar_Pervasives_Native_Some)
    np = x.v;
  else
    np = KRML_EABORT(node__uint64_t *, "unreachable (pattern matches are exhaustive in F*)");
  node__uint64_t n = *np;
  uint64_t value = n.head;
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ next = n.tail;
  KRML_HOST_FREE(np);
  return
    (
      (__FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t){
        .fst = next,
        .snd = value
      }
    );
}

static FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_
fst__FStar_Pervasives_Native_option__Pulse_Lib_LinkedList_node_uint64_t__uint64_t(
  __FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t x
)
{
  return x.fst;
}

static uint64_t
snd__FStar_Pervasives_Native_option__Pulse_Lib_LinkedList_node_uint64_t__uint64_t(
  __FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t x
)
{
  return x.snd;
}

static uint64_t pop(FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st)
{
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ curr = *st;
  __FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t__uint64_t
  r = pop__uint64_t(curr);
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_
  new_ll = fst__FStar_Pervasives_Native_option__Pulse_Lib_LinkedList_node_uint64_t__uint64_t(r);
  uint64_t
  v = snd__FStar_Pervasives_Native_option__Pulse_Lib_LinkedList_node_uint64_t__uint64_t(r);
  *st = new_ll;
  return v;
}

static void
darken_if_white(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st,
  uint64_t h_addr
)
{
  uint64_t hdr = read_word(heap, h_addr);
  Pulse_Lib_Header_color_sem c = getColor(hdr);
  uint64_t obj = f_address(h_addr);
  if (c == white)
  {
    uint64_t new_hdr = Pulse_Spec_GC_Object_colorHeader(hdr, Pulse_Lib_Header_Gray);
    write_word(heap, h_addr, new_hdr);
    push(st, obj);
  }
}

static void
check_and_darken(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st,
  uint64_t v
)
{
  bool is_ptr = is_pointer(v);
  if (is_ptr)
  {
    uint64_t target_hdr_raw = v - mword;
    uint64_t target_hdr = target_hdr_raw;
    darken_if_white(heap, st, target_hdr);
  }
}

static void
push_step_body(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st,
  uint64_t h_addr,
  uint64_t curr_i
)
{
  uint64_t v = read_field(heap, h_addr, curr_i);
  check_and_darken(heap, st, v);
}

static void
push_children(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st,
  uint64_t h_addr,
  uint64_t wz
)
{
  uint64_t obj = f_address(h_addr);
  KRML_MAYBE_UNUSED_VAR(obj);
  uint64_t i = 1ULL;
  uint64_t __anf0 = i;
  bool cond = __anf0 <= wz;
  while (cond)
  {
    uint64_t curr_i = i;
    push_step_body(heap, st, h_addr, curr_i);
    i = curr_i + 1ULL;
    uint64_t __anf0 = i;
    cond = __anf0 <= wz;
  }
}

static void
mark_step(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st
)
{
  uint64_t f_addr = pop(st);
  uint64_t h_addr_raw = f_addr - mword;
  uint64_t h_addr = h_addr_raw;
  uint64_t hdr = read_word(heap, h_addr);
  uint64_t wz = getWosize(hdr);
  uint64_t tag = getTag(hdr);
  uint64_t new_hdr = makeHeader(wz, black, tag);
  write_word(heap, h_addr, new_hdr);
  if (!(tag >= no_scan_tag))
    push_children(heap, st, h_addr, wz);
}

static void
mark_loop(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st
)
{
  uint64_t fuel_init = FStar_UInt64_uint_to_t(heap_size) / mword;
  bool go = true;
  uint64_t fuel_ref = fuel_init;
  while (go)
  {
    bool empty = is_empty(st);
    if (empty)
      go = false;
    else
    {
      mark_step(heap, st);
      uint64_t cur_fuel = fuel_ref;
      fuel_ref = cur_fuel - 1ULL;
    }
  }
}

static uint64_t field1_of(uint64_t h_addr)
{
  return h_addr + mword;
}

static uint64_t sweep_white_spec(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  if (wz > 0ULL)
  {
    uint64_t obj = Pulse_Spec_GC_Heap_f_address(h_addr);
    KRML_MAYBE_UNUSED_VAR(obj);
    uint64_t field1_addr = field1_of(h_addr);
    write_word(heap, field1_addr, fp);
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t blue_hdr = makeHeader(getWosize(hdr), blue, getTag(hdr));
    write_word(heap, h_addr, blue_hdr);
    return Pulse_Spec_GC_Heap_f_address(h_addr);
  }
  else
  {
    uint64_t obj = Pulse_Spec_GC_Heap_f_address(h_addr);
    KRML_MAYBE_UNUSED_VAR(obj);
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t blue_hdr = makeHeader(getWosize(hdr), blue, getTag(hdr));
    write_word(heap, h_addr, blue_hdr);
    return Pulse_Spec_GC_Heap_f_address(h_addr);
  }
}

static uint64_t
sweep_black_spec(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t hdr, uint64_t fp)
{
  uint64_t new_hdr = makeHeader(wz, white, getTag(hdr));
  write_word(heap, h_addr, new_hdr);
  return fp;
}

static uint64_t sweep_white_case(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  return sweep_white_spec(heap, h_addr, wz, fp);
}

static uint64_t sweep_black_case(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  uint64_t hdr = read_word(heap, h_addr);
  sweep_black_spec(heap, h_addr, wz, hdr, fp);
  return fp;
}

static uint64_t sweep_object(heap_t heap, uint64_t h_addr, uint64_t wz, uint64_t fp)
{
  uint64_t hdr = read_word(heap, h_addr);
  Pulse_Lib_Header_color_sem color = getColor(hdr);
  if (color == white)
    return sweep_white_case(heap, h_addr, wz, fp);
  else if (color == black)
    return sweep_black_case(heap, h_addr, wz, fp);
  else
    return fp;
}

static uint64_t next_object(uint64_t h_addr, uint64_t wz)
{
  uint64_t skip = 1ULL + wz;
  uint64_t offset = skip * mword;
  return h_addr + offset;
}

static void sweep_loop(heap_t heap, uint64_t *current, uint64_t *free_ptr)
{
  uint64_t __anf0 = *current;
  bool cond = __anf0 + mword < FStar_UInt64_uint_to_t(heap_size);
  while (cond)
  {
    uint64_t h_addr_raw = *current;
    uint64_t h_addr = h_addr_raw;
    uint64_t hdr = read_word(heap, h_addr);
    uint64_t wz = getWosize(hdr);
    uint64_t cur_fp = *free_ptr;
    uint64_t new_fp = sweep_object(heap, h_addr, wz, cur_fp);
    *free_ptr = new_fp;
    uint64_t next_addr = next_object(h_addr, wz);
    *current = next_addr;
    uint64_t __anf0 = *current;
    cond = __anf0 + mword < FStar_UInt64_uint_to_t(heap_size);
  }
}

static uint64_t sweep(heap_t heap, uint64_t fp)
{
  uint64_t cur_init = zero_addr;
  uint64_t current = cur_init;
  uint64_t free_ptr = fp;
  sweep_loop(heap, &current, &free_ptr);
  return free_ptr;
}

uint64_t
collect(
  heap_t heap,
  FStar_Pervasives_Native_option___Pulse_Lib_LinkedList_node__uint64_t_ *st,
  uint64_t fp
)
{
  mark_loop(heap, st);
  return sweep(heap, fp);
}

