/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/generational/../fstar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -bundle GC.Gen.Impl+GC.Gen.Impl.MinorHeap+GC.Impl+GC.Impl.Allocator=GC.Gen.Impl.*,GC.Impl.*[rename=GC_Gen_Impl] -bundle FStar.Pervasives.Native -bundle GC.Gen.Base,GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Gen.Impl -no-prefix GC.Gen.Impl.MinorHeap -no-prefix GC.Gen.Impl.Cheney -no-prefix GC.Gen.Impl.Promote -no-prefix GC.Gen.Impl.UpdatePtrs -no-prefix GC.Gen.Base -no-prefix GC.Impl -no-prefix GC.Impl.Mark -no-prefix GC.Impl.MarkBounded -no-prefix GC.Impl.Sweep -no-prefix GC.Impl.Fields -no-prefix GC.Impl.Closure -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -no-prefix GC.Impl.Allocator -no-prefix GC.Impl.FusedSweepCoalesce -no-prefix GC.Impl.Coalesce -warn-error -2-9-15 _output/GC_Gen_Impl.krml _output/GC_Gen_Impl_MinorHeap.krml _output/GC_Gen_Impl_Cheney.krml _output/GC_Gen_Impl_Promote.krml _output/GC_Gen_Impl_UpdatePtrs.krml _output/GC_Gen_Base.krml _output/GC_Impl.krml _output/GC_Impl_Fields.krml _output/GC_Impl_Closure.krml _output/GC_Impl_Mark.krml _output/GC_Impl_MarkBounded.krml _output/GC_Impl_Sweep.krml _output/GC_Impl_Coalesce.krml _output/GC_Impl_FusedSweepCoalesce.krml _output/GC_Impl_Allocator.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml _output/FStar_Pervasives_Native.krml
  F* version: <unknown>
  KaRaMeL version: 772e4f63642524f6fb3c15fcb1b9398dd6afea7f
 */

#include "internal/GC_Gen_Base_GC_Spec_GC_Lib_Header_GC_Lib_Address.h"

uint64_t GC_Spec_Base_heap_size_u64 = 1024ULL;

bool GC_Lib_Header_uu___is_Black(GC_Lib_Header_color_sem projectee)
{
  switch (projectee)
  {
    case GC_Lib_Header_Black:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

krml_checked_int_t minor_heap_size = (krml_checked_int_t)2048;

uint64_t minor_heap_size_u64 = 2048ULL;

uint64_t max_young_wosize_u64 = 128ULL;

