/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -warn-error -2-9-11-15-17 -bundle Pulse.Lib.GC+Pulse.Lib.GC.Mark+Pulse.Lib.GC.Sweep+Pulse.Lib.GC.Fields+Pulse.Lib.GC.Closure+Pulse.Lib.GC.Heap+Pulse.Lib.GC.Object+Pulse.Lib.GC.Stack=Pulse.Lib.GC.*[rename=PulseGC] -bundle FStar.*,Pulse.*,PulseCore.*,Prims -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/Pulse_Lib_GC_Sweep.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_FStar_Pulse_PulseCore_Prims_H
#define internal_FStar_Pulse_PulseCore_Prims_H

#include "krmllib.h"
#include "../PulseGC_compat.h"

/* Prims: checked integer operations (spec-level, inlined for extraction) */
static inline krml_checked_int_t Prims_op_Multiply(krml_checked_int_t x, krml_checked_int_t y) {
  return x * y;
}
static inline krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y) {
  return x + y;
}
static inline krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y) {
  return x % y;
}
static inline bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x, krml_checked_int_t y) {
  return x >= y;
}
static inline bool Prims_op_LessThan(krml_checked_int_t x, krml_checked_int_t y) {
  return x < y;
}


#define internal_FStar_Pulse_PulseCore_Prims_H_DEFINED
#endif /* internal_FStar_Pulse_PulseCore_Prims_H */
