/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -bundle GC.Impl+GC.Impl.Allocator=GC.Impl.*[rename=GC_Impl] -bundle FStar.Pervasives.Native -bundle GC.Spec.*,GC.Lib.Header,GC.Lib.Address -no-prefix GC.Impl -no-prefix GC.Impl.Mark -no-prefix GC.Impl.Sweep -no-prefix GC.Impl.Fields -no-prefix GC.Impl.Closure -no-prefix GC.Impl.Heap -no-prefix GC.Impl.Object -no-prefix GC.Impl.Stack -no-prefix GC.Impl.Allocator -warn-error -2-9-15 _output/GC_Impl_Fields.krml _output/GC_Impl_Closure.krml _output/GC_Impl_Mark.krml _output/GC_Impl_Sweep.krml _output/GC_Impl.krml _output/GC_Impl_Allocator.krml _output/GC_Impl_Heap.krml _output/GC_Impl_Object.krml _output/GC_Impl_Stack.krml _output/GC_Spec_Base.krml _output/GC_Spec_Heap.krml _output/GC_Spec_Object.krml _output/GC_Lib_Header.krml _output/GC_Lib_Address.krml _output/FStar_Pervasives_Native.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_Prims_H
#define internal_Prims_H

#include "krmllib.h"

extern krml_checked_int_t Prims_op_Division(krml_checked_int_t x, krml_checked_int_t y);


#define internal_Prims_H_DEFINED
#endif /* internal_Prims_H */
