/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /home/nswamy/workspace/pulse-verified-gc/mark-and-sweep/../FStar/karamel/krml -tmpdir _extract -skip-compilation -skip-linking -library Pulse.Spec.GC.Base -library Pulse.Spec.GC.Heap -library Pulse.Spec.GC.Object -library Pulse.Lib.Header -library Pulse.Lib.Address -bundle Pulse.Lib.GC=Pulse.Lib.GC.* -bundle FStar.Pervasives.Native -bundle Pulse.Spec.GC.*,Pulse.Lib.Header,Pulse.Lib.Address -no-prefix Pulse.Lib.GC -no-prefix Pulse.Lib.GC.Mark -no-prefix Pulse.Lib.GC.Sweep -no-prefix Pulse.Lib.GC.Fields -no-prefix Pulse.Lib.GC.Closure -no-prefix Pulse.Lib.GC.Heap -no-prefix Pulse.Lib.GC.Object -no-prefix Pulse.Lib.GC.Stack -warn-error -2-9-15 _output/Pulse_Lib_GC_Fields.krml _output/Pulse_Lib_GC_Closure.krml _output/Pulse_Lib_GC_Mark.krml _output/Pulse_Lib_GC_Sweep.krml _output/Pulse_Lib_GC.krml _output/Pulse_Lib_GC_Heap.krml _output/Pulse_Lib_GC_Object.krml _output/Pulse_Lib_GC_Stack.krml _output/FStar_Pervasives_Native.krml _output/Pulse_Spec_GC_Base.krml _output/Pulse_Spec_GC_Heap.krml _output/Pulse_Spec_GC_Object.krml _output/Pulse_Lib_Header.krml _output/Pulse_Lib_Address.krml
  F* version: <unknown>
  KaRaMeL version: <unknown>
 */

#ifndef internal_Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address_H
#define internal_Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address_H

#include "krmllib.h"

extern uint64_t Pulse_Spec_GC_Base_mword;

extern krml_checked_int_t Pulse_Spec_GC_Base_heap_size;

extern uint64_t Pulse_Spec_GC_Base_zero_addr;

#define Pulse_Lib_Header_White 0
#define Pulse_Lib_Header_Gray 1
#define Pulse_Lib_Header_Blue 2
#define Pulse_Lib_Header_Black 3

typedef uint8_t Pulse_Lib_Header_color_sem;

extern uint8_t Pulse_Spec_GC_Heap_uint64_to_uint8(uint64_t x);

extern uint64_t
Pulse_Spec_GC_Heap_combine_bytes(
  uint8_t b0,
  uint8_t b1,
  uint8_t b2,
  uint8_t b3,
  uint8_t b4,
  uint8_t b5,
  uint8_t b6,
  uint8_t b7
);

extern uint64_t Pulse_Spec_GC_Heap_f_address(uint64_t h_addr);

extern uint64_t
Pulse_Spec_GC_Object_colorHeader(uint64_t header, Pulse_Lib_Header_color_sem new_color);


#define internal_Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address_H_DEFINED
#endif /* internal_Pulse_Spec_GC_Pulse_Lib_Header_Pulse_Lib_Address_H */
